import { Geist, Geist_Mono ,Playfair_Display,Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

const playfair = Playfair_Display({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700', '800', '900'],
  variable: '--font-playfair',
})
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"], // choose the weights you need
  variable: "--font-roboto",
});


export const metadata = {
  title: "Leading Cybersecurity Solutions for Modern Businesses",
  description: "Generated by create next app",
  icons: {
    icon: "/titlelogo.svg",  // <-- use your SVG file here
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${playfair.variable} ${roboto.variable}`}>
      <body className="min-h-screen flex flex-col bg-white">
        <Navbar />
        
        {/* Main content grows to push footer down */}
        <main className="grow">
          {children}
        </main>

        <Footer />
      </body>
    </html>
  );
}
